on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

name: Build and test

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # env:
    #   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #   TURBO_TEAM: ${{ secrets.TURBO_TEAM }} setup for remote caching
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.15.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Prisma
        working-directory: ./packages/db
        run: pnpm db:generate:charters

      - name: Build
        run: pnpm build

      - name: Install playwright and browsers
        working-directory: ./packages/e2e-tests
        run: npx playwright install

      - name: run e2e playwright tests
        run: pnpm test:e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
